/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available session sources
         * @description Returns all configured session sources and their metadata
         */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{source}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sessions for a source
         * @description Returns paginated session list with lightweight metadata. No full event data.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{source}/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session metadata
         * @description Returns session metadata without events
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{source}/sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session events
         * @description Returns normalized events for a session. Supports optional pagination.
         */
        get: operations["getSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{source}/sessions/{sessionId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get timeline data for time analysis */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{source}/sessions/{sessionId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export session as zip */
        get: operations["exportSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{source}/sessions/{sessionId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tags for a session */
        get: operations["getSessionTags"];
        /** Set tags for a session */
        put: operations["setSessionTags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{source}/sessions/{sessionId}/insight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get agent review status/result */
        get: operations["getInsight"];
        put?: never;
        /** Generate agent review */
        post: operations["generateInsight"];
        /** Delete agent review */
        delete: operations["deleteInsight"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all known tags across all sources */
        get: operations["listAllTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a session from zip */
        post: operations["importSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Source: {
            /** @description Source identifier used in URL path */
            id: string;
            /** @description Human-readable display name */
            label: string;
            /** @description Total number of sessions for this source */
            sessionCount?: number;
        };
        SessionSummary: {
            id: string;
            source: string;
            title?: string;
            /** @enum {string} */
            sessionStatus?: "completed" | "wip" | "error";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            eventCount?: number;
            /** @description Duration in milliseconds */
            duration?: number;
            model?: string;
            producer?: string;
            tags?: string[];
        };
        Session: components["schemas"]["SessionSummary"] & {
            usage?: {
                modelMetrics?: {
                    [key: string]: {
                        usage?: {
                            inputTokens?: number;
                            outputTokens?: number;
                            cacheReadTokens?: number;
                            cacheWriteTokens?: number;
                        };
                        requests?: {
                            count?: number;
                        };
                    };
                };
            };
        };
        SessionList: {
            sessions: components["schemas"]["SessionSummary"][];
            hasMore?: boolean;
            totalSessions?: number;
        };
        Event: {
            stableId?: string;
            /** @description Event type (e.g. user.message, assistant.message, tool.call, tool.result, subagent.started, subagent.completed) */
            type: string;
            /** Format: date-time */
            timestamp: string;
            /** @description Event-specific payload (varies by type) */
            data?: Record<string, never>;
        };
        PaginatedEvents: {
            events: components["schemas"]["Event"][];
            pagination: {
                total: number;
                limit: number;
                offset: number;
                hasMore: boolean;
            };
        };
        /** @description Structured timeline data for time analysis visualization */
        Timeline: Record<string, never>;
        Insight: {
            /** @enum {string} */
            status?: "not_started" | "generating" | "completed" | "timeout";
            /** @description Markdown content of the agent review */
            content?: string;
            /** Format: date-time */
            generatedAt?: string;
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Session source identifier */
        source: "copilot-cli" | "copilot-chat" | "claude" | "modernize" | "pi-mono";
        sessionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated session list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getSessionEvents: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][] | components["schemas"]["PaginatedEvents"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    exportSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zip file download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSessionTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    setSessionTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tags: string[];
                };
            };
        };
        responses: {
            /** @description Tags updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        tags?: string[];
                    };
                };
            };
        };
    };
    getInsight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insight data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insight"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    generateInsight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insight generation started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "generating";
                    };
                };
            };
            /** @description Insight already exists or is generating */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteInsight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session source identifier */
                source: components["parameters"]["source"];
                sessionId: components["parameters"]["sessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insight deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAllTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    importSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Session imported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        sessionId?: string;
                        source?: string;
                    };
                };
            };
        };
    };
}
